[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[lib]

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
valida-rs = { git = "https://github.com/lita-xyz/valida-rs.git", branch = "main" }
